### ISSUE TITLE
Git history

### ISSUE THREAD

**Issue by glebm** [retrofw/buildroot#4]
Could you please restore the git history of this repo, so that all the commits from upstream buildroot up to the point where it was forked are present?

**Comment by pingflood** [comment]
This repository was built over the buildroot-2018.02.11 release, available here:
https://buildroot.org/downloads/buildroot-2018.02.11.tar.gz

The repository was initialized with that release and the RetroFW changes were committed over it.

Since the changes are specific for this device series and we're not planning any PR, forking the upstream repository isn't planned at this moment.

For now I'll tag this as #wontfix, but it doesn't means we will not get back on this subject in the future.
